# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool: Default

variables:
  solution: '**/Storefront.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.sln'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/StoreTests/*.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    zipAfterPublish: true
    publishWebProjects: true
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(ff297f74-9e4d-4595-b6e8-6652d237fba8)'
    appType: 'webApp'
    WebAppName: 'p1storefront'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'